<a href="https://colab.research.google.com/github/Nataliaspindola/Naty-C-/blob/main/Aula1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
df= pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

In [4]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133349 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  float64
 1   experience_level    133349 non-null  object
 2   employment_type     133349 non-null  object
 3   job_title           133349 non-null  object
 4   salary              133349 non-null  int64
 5   salary_currency     133349 non-null  object
 6   salary_in_usd       133349 non-null  int64
 7   employee_residence  133349 non-null  object
 8   remote_ratio        133349 non-null  int64
 9   company_location    133349 non-null  object
 10  company_size        133349 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 11.2+ MB

In [6]:
df.describe()

           work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [7]:
df.shape

(133349, 11)

In [11]:
linhas, colunas = df.shape[0], df.shape[1]
print("Colunas:", linhas)
print("Linhas:", colunas)

Colunas: 133349
Linhas: 11

In [30]:
df.columns

Index(['ano_trabalho', 'nivel_experiencia', 'contrato', 'cargo', 'salario',
       'moeda_salario', 'salario_em_usd', 'residencia_empregado',
       'taxa_remoto', 'localizacao_empresa', 'tamanho_empresa'],
      dtype='object')

In [27]:
renomear_colunas = {'ano', 'nivel_experiencia', 'contrato', 'cargo', 'salario',
       'moeda_salario', 'usd', 'residencia',
       'remoto', 'localizacao_empresa', 'tamanho_empresa'}

In [25]:
df["nivel_experiencia"].value_counts()

nivel_experiencia
SE    77241
MI    40465
EN    12443
EX     3200
Name: count, dtype: int64

In [39]:
df["contrato"].value_counts()

contrato
FT    132563
CT       394
PT       376
FL        16
Name: count, dtype: int64

In [34]:
df["tamanho_empresa"].value_counts()

tamanho_empresa
M    129561
L      3574
S       214
Name: count, dtype: int64

In [42]:
# Translate remote ratio categories to Portuguese
df['taxa_remoto'] = df['taxa_remoto'].replace({
    0: 'Presencial',
    50: 'Híbrido',
    100: 'Remoto'
})

# Display value counts of the translated column
print("Contagem das categorias de taxa remota (em português):")
display(df["taxa_remoto"].value_counts())

Contagem das categorias de taxa remota (em português):

taxa_remoto
Presencial    105312
Remoto         27718
Híbrido          319
Name: count, dtype: int64

In [43]:
df.head()

,ano_trabalho,nivel_experiencia,contrato,cargo,salario,moeda_salario,salario_em_usd,residencia_empregado,taxa_remoto,localizacao_empresa,tamanho_empresa
0,2025.0,Sênioridade,FT,Solutions Engineer,214000,USD,214000,US,Remoto,US,Média
1,2025.0,Sênioridade,FT,Solutions Engineer,136000,USD,136000,US,Remoto,US,Média
2,2025.0,Pleno,FT,Data Engineer,158800,USD,158800,AU,Presencial,AU,Média
3,2025.0,Pleno,FT,Data Engineer,139200,USD,139200,AU,Presencial,AU,Média
4,2025.0,Júnior,FT,Data Engineer,90000,USD,90000,US,Presencial,US,Média

In [45]:
df.describe(include="object")

,nivel_experiencia,contrato,cargo,moeda_salario,residencia_empregado,taxa_remoto,localizacao_empresa,tamanho_empresa
count,133349,133349,133349,133349,133349,133349,133349,133349
unique,4,4,390,26,102,3,95,3
top,Sênioridade,FT,Data Scientist,USD,US,Presencial,US,Média
freq,77241,132563,17314,126140,119579,105312,119641,129561

In [46]:
df.describe()

        ano_trabalho       salario  salario_em_usd
count  133339.000000  1.333490e+05   133349.000000
mean     2024.358770  1.632833e+05   157617.272098
std         0.680627  2.173860e+05    74288.363097
min      2020.000000  1.400000e+04    15000.000000
25%      2024.000000  1.060200e+05   106000.000000
50%      2024.000000  1.470000e+05   146206.000000
75%      2025.000000  1.990000e+05   198000.000000
max      2025.000000  3.040000e+07   800000.000000